# Generated by Django 4.0.3 on 2022-04-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='description',
            field=models.CharField(default='describe the flavor experience', max_length=250),
        ),
    ]
