# Generated by Django 4.0.3 on 2022-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_cookie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='description',
            field=models.CharField(default=':)', max_length=250),
        ),
    ]
