# Generated by Django 4.0.3 on 2022-04-02 23:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_cookie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
