# Generated by Django 4.0.3 on 2022-04-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_bakery_alter_cookie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='bakery',
            field=models.ManyToManyField(to='main_app.bakery'),
        ),
    ]
