# Generated by Django 4.0.3 on 2022-04-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_cookie_bakery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakery',
            old_name='webiste',
            new_name='website',
        ),
    ]
