# Generated by Django 4.0.3 on 2022-04-12 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_rename_webiste_bakery_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='bakery',
            new_name='bakeries',
        ),
    ]
