# Generated by Django 4.0.3 on 2022-04-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_bakery_cookie_bakeries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='bakeries',
            new_name='bakery',
        ),
    ]
